### ISSUE TITLE
Failed to resolve entry for package "@maxgraph/core"

### ISSUE THREAD

**Issue by prophetchen** [tbouffard/maxgraph-integration-examples#12]
entry for package "@maxgraph/core". The package may have incorrect main/module/exports specified in its package.json.
20:46:10 [vite] Internal server error: Failed to resolve entry for package "@maxgraph/core". The package may have incorrect main/module/exports specified in its package.json: Failed to resolve entry for package "@maxgraph/core". The package may have incorrect main/module/exports specified in its package.json.
  Plugin: vite:import-analysis
  File: /Users/prophet/work/maxgraph-integration-examples/projects/vitejs-ts/src/main.ts
      at packageEntryFailure (/Users/prophet/work/maxgraph-integration-examples/projects/vitejs-ts/node_modules/vite/dist/node/chunks/dep-80fe9c6b.js:40945:11)
      at resolvePackageEntry (/Users/prophet/work/maxgraph-integration-examples/projects/vitejs-ts/node_modules/vite/dist/node/chunks/dep-80fe9c6b.js:40941:9)
      at tryNodeResolve (/Users/prophet/work/maxgraph-integration-examples/projects/vitejs-ts/node_modules/vite/dist/node/chunks/dep-80fe9c6b.js:40748:20)
      at Context.resolveId (/Users/prophet/work/maxgraph-integration-examples/projects/vitejs-ts/node_modules/vite/dist/node/chunks/dep-80fe9c6b.js:40556:28)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async Object.resolveId (/Users/prophet/work/maxgraph-integration-examples/projects/vitejs-ts/node_modules/vite/dist/node/chunks/dep-80fe9c6b.js:39229:32)
      at async TransformContext.resolve (/Users/prophet/work/maxgraph-integration-examples/projects/vitejs-ts/node_modules/vite/dist/node/chunks/dep-80fe9c6b.js:39003:23)
      at async normalizeUrl (/Users/prophet/work/maxgraph-integration-examples/projects/vitejs-ts/node_modules/vite/dist/node/chunks/dep-80fe9c6b.js:58323:34)
      at async TransformContext.transform (/Users/prophet/work/maxgraph-integration-examples/projects/vitejs-ts/node_modules/vite/dist/node/chunks/dep-80fe9c6b.js:58478:57)
      at async Object.transform (/Users/prophet/work/maxgraph-integration-examples/projects/vitejs-ts/node_modules/vite/dist/node/chunks/dep-80fe9c6b.js:39292:30)

**Comment by tbouffard** [comment]
Hi can you provide more information?
How did you initialize the project? Did you follow the Readme and which solution did you use to integrate the npm package you locally built?

**Comment by tbouffard** [comment]
I have just realized that the Readme is missing an important information.
The maxGraph development branch should not be use for now to build the nom package.
In my tests, I used https://github.com/maxGraph/maxGraph/pull/87 that is under review.
I suggest you to use the branch of this Pull Request to build the npm package.
I will update the Readme with that later.

**Comment by prophetchen** [comment]
Thank you very much for your answer. I'll have a try,:D.

**Comment by tbouffard** [comment]
@prophetchen the maxGraph development branch now contains everything to make the examples of this repository work.
I have been able to build the npm package from development branch and use them here: see  #14

**Comment by tbouffard** [comment]
I am closing this issue as there is no activity here.
Feel free to reopen if you still have problems.
